export const actionTypes = {
  SEARCH_DATA_RESPONSE: 'SEARCH_DATA_RESPONSE',
  PRESERVE_SEARCH_HISTORY: 'PRESERVE_SEARCH_HISTORY',
  SET_SEARCH_HISTORY: 'SET_SEARCH_HISTORY',
  SET_SEARCH_QUERY: 'SET_SEARCH_QUERY'
}